### ISSUE TITLE
bbb_recordings_published error

### ISSUE THREAD

**Issue by penguennoktanet** [greenstatic/bigbluebutton-exporter#23] opened 2020-05-05 07:14 UTC
One of my servers declare bbb_recordings_published is 0. But bbb-record shows published records and /var/bigbluebutton/published/presentation has 996 folders.

If you reqire any additional data, please let me know...

**Comment by greenstatic** [comment] 2020-05-06 11:49
`bbb_recordings_published 0` does Grafana report this or the raw metrics of the exporter?

The correct way to approach this is to figure out of BBB is reporting the wrong value in it's XML API or if the exporter has a bug.

I just [updated the documentation](https://bigbluebutton-exporter.greenstatic.dev/debugging/) with the instructions how to view the XML API responses the exporter gets from BBB. I suggest you take a look if the XML API response contains these published recordings or not.

**Comment by greenstatic** [comment] 2020-05-10 21:41
Have you managed to figure out your issue?

**Comment by penguennoktanet** [comment] 2020-05-13 07:52
Sorry for late response. I was too busy with other stuff.

> `bbb_recordings_published 0` does Grafana report this or the raw metrics of the exporter?

They both report the same value. But here is the catch (output from the BBB-exporter);
`bbb_recordings_published 0.0
bbb_recordings_deleted 0.0
bbb_api_latency_count{endpoint="getRecordings",parameters="state=published"} 8187.0
bbb_api_latency_count{endpoint="getRecordings",parameters="state=unpublished"} 8187.0
bbb_api_latency_count{endpoint="getRecordings",parameters="state=deleted"} 8187.0`

> I just [updated the documentation](https://bigbluebutton-exporter.greenstatic.dev/debugging/) with the instructions how to view the XML API responses the exporter gets from BBB. I suggest you take a look if the XML API response contains these published recordings or not.

Seems like I could not enable the debug mode (I hate docker, never care to learn it in detail). But when I traced logs of it, I saw this;

`bbb-exporter    | 2020-05-13 07:45:16,396 [INFO]: Collecting metrics from BigBlueButton API
bbb-exporter    | 2020-05-13 07:45:36,340 [INFO]: Collecting metrics from BigBlueButton API
bbb-exporter    | 2020-05-13 07:46:21,859 [ERROR]: Non 2xx HTTP status code response
bbb-exporter    | 2020-05-13 07:46:21,859 [ERROR]: <html>
bbb-exporter    | <head><title>404 Not Found</title></head>
bbb-exporter    | <body bgcolor="white">
bbb-exporter    | <center><h1>404 Not Found</h1></center>
bbb-exporter    | <hr><center>nginx/1.10.3 (Ubuntu)</center>
bbb-exporter    | </body>
bbb-exporter    | </html>
`

**Comment by greenstatic** [comment] 2020-05-13 08:00
I suggest you update to the recently released v0.3.0 and if you don't like Docker, we have a [Systemd installation guide](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installation-type-matrix). You can also add `DEBUG=true` to the Systemd installation to enable detailed logs.

The error you posted seems like:
1. The exporter is visiting the wrong API endpoint. This could be caused by a miss configured API_BASE_URL, but if you are getting proper metric values for other metrics this shouldn't be the case.
2. You have a miss configured Nginx config that has some weird location rewrite rules.

**Comment by penguennoktanet** [comment] 2020-05-13 08:29
> I suggest you update to the recently released v0.3.0 and if you don't like Docker, we have a [Systemd installation guide](https://bigbluebutton-exporter.greenstatic.dev/getting-started/#installation-type-matrix). You can also add `DEBUG=true` to the Systemd installation to enable detailed logs.

I always deploy with "BBB_EXPORTER_VERSION=latest docker-compose up -d".

Nice touch on systemd installation. That wasn't there when I setup the systems (or I missed them). If I got some spare time, I will switch to systemd (old habits die hard, I still miss SysVinit scripts :) )
 
> The error you posted seems like:
> 1. The exporter is visiting the wrong API endpoint. This could be caused by a miss configured API_BASE_URL, but if you are getting proper metric values for other metrics this shouldn't be the case.

That's right. bbb_meetings, bbb_meetings_participants, bbb_meetings_listeners etc seems to be fine.

> 2. You have a miss configured Nginx config that has some weird location rewrite rules.

Don't think that's the issue because of 2 reasons;
1) That metric was good after the installation and for following 6 weeks.
2) Some of the servers' published counts seem ok with no meeting on going. But when the meetings start and servers CPU usage raises (notting critical, %30-40 usage only) number seems to be malfunctioning.

**Comment by greenstatic** [comment] 2020-05-13 09:01
Im not sure if `BBB_EXPORTER_VERSION=latest docker-compose up -d"` pulls the latest docker image every time.

Yes you are correct, the systemd installation guide was added recently.

Good luck debugging, do report back with your findings :).

**Comment by greenstatic** [comment] 2020-05-27 19:00
Are you still experiencing this issue in v0.4.0?

**Comment by greenstatic** [comment] 2020-06-09 19:39
Closing this for now. If you experience the issue again, reopen this issue or open another one.

**Closed by greenstatic** 2020-06-09 19:39 UTC
Labels: support

**Comment by SimonBrigadier** [comment] 2022-01-20 13:58
We have a similar problem. bbb_recordings_deleted has the following value: -4481.0, but the folders in /var/bigbluebutton/deleted/presentation/: 7 and API https://<url>/bigbluebutton/api/getRecordings?state=deleted also give 7 records. I turned on the debug mode, I do not see anything problematic in the logs. I used the v0.6.0 exporter image, I also tried to run both v0.5.1 and v0.5.2, but the result is the same. The path /var/bigbluebutton is available to the exporter because bbb_recordings_published and bbb_recordings_unpublished are correct. Before that, we migrated the bbb server from the bbb22 version to the bbb24 version and copied only /var/bigbluebutton/published/, /var/bigbluebutton/unpublished/ and /var/bigbluebutton/recording/raw/ from the old server due to the large volume of records. Could this somehow affect bbb_recordings_deleted? What else can be done to solve this problem?
