### ISSUE TITLE
metrics returns 404

### ISSUE THREAD

**Issue by shankar-bavan** [greenstatic/bigbluebutton-exporter#102] opened 2021-10-09 07:23 UTC
I'm setting up BigBlueButton exporter on separate server.

I added this configuration in BBB server

```
# BigBlueButton Exporter (metrics) 
location /metrics/ {
    auth_basic "Metrics Exporter";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://127.0.0.1:9688/;
    include proxy_params;
}

```

followed this guide
https://bigbluebutton-exporter.greenstatic.dev/installation/bigbluebutton_exporter/#6-add-nginx-site-configuration

then I visited to bbbdomain/metrics
it was asked to enter the username and password.

then I got 404 Not Found error

this is from Prometheus

![image](https://user-images.githubusercontent.com/48729909/136648481-d82061ba-63db-48fc-81e6-48e971c5a20a.png)

**Comment by greenstatic** [comment] 2022-06-02 09:36
Did you manage to solve your issue?
I'll be closing this issue for now, feel free to reopen in case the issue is not solved.

**Closed by greenstatic** 2022-06-02 09:36 UTC
Labels: support
