### ISSUE TITLE
Bigbluebutton 2.4 API error

### ISSUE THREAD

**Issue by Nick64M** [greenstatic/bigbluebutton-exporter#104] opened 2021-12-04 04:09 UTC
Bigbluebutton 2.4 API error. BBB 2.36 all ok

**Comment by greenstatic** [comment] 2021-12-04 08:01
What kind of error are you receiving? Could you send a snippet of the output?

**Comment by Nick64M** [comment] 2021-12-04 08:56
BBB API Offline. The rest is displayed.
https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=ops2cvpehp6#attid%253Datt_17d838318365714e_0.1_7385f06e_f8019d53_16251820_62f8c2c2_2538ef39%25252Fmonitoryng.jpg

**Comment by greenstatic** [comment] 2021-12-04 09:06
Could you show bbb-exporter’s console logs?

**Comment by Nick64M** [comment] 2021-12-04 09:09
Where to look for console logs?

**Comment by greenstatic** [comment] 2021-12-04 09:11
How did you install the exporter?

**Comment by Nick64M** [comment] 2021-12-04 09:22
I used the site https://bigbluebutton.ru/monitoring-bigbluebutton.html#

**Comment by greenstatic** [comment] 2021-12-04 10:36
It seems like the video follows the all in one monitoring stack instructions (https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/). In this case the logs are available using docker. In your server shell run:

1. docker ps
Here find the name of the bbb exporter container
2. docker logs <name of bbb exporter container>

**Comment by Nick64M** [comment] 2021-12-06 08:01
I do not understand why, but started working. Only online information is not updated. Preliminary data is displayed.

Logi found
 prometheus and grafana not install
Attaching to node_exporter
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:105 msg="Enabled collectors"
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=arp
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=bcache
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=bonding
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=btrfs
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=conntrack
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=cpu
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=cpufreq
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=diskstats
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=edac
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=entropy
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=filefd
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=filesystem
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=hwmon
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=infiniband
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=ipvs
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=loadavg
node_exporter    | level=info ts=2021-12-02T20:01:30.185Z caller=node_exporter.go:112 collector=mdadm
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=meminfo
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=netclass
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=netdev
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=netstat
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=nfs
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=nfsd
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=powersupplyclass
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=pressure
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=rapl
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=schedstat
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=sockstat
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=softnet
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=stat
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=textfile
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=thermal_zone
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=time
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=timex
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=udp_queues
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=uname
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=vmstat
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=xfs
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:112 collector=zfs
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=node_exporter.go:191 msg="Listening on" address=127.0.0.1:9100
node_exporter    | level=info ts=2021-12-02T20:01:30.186Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false
node_exporter    | level=info ts=2021-12-02T20:03:47.250Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
node_exporter    | level=info ts=2021-12-02T20:03:47.250Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:105 msg="Enabled collectors"
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=arp
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=bcache
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=bonding
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=btrfs
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=conntrack
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=cpu
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=cpufreq
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=diskstats
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=edac
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=entropy
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=filefd
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=filesystem
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=hwmon
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=infiniband
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=ipvs
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=loadavg
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=mdadm
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=meminfo
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=netclass
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=netdev
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=netstat
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=nfs
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=nfsd
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=powersupplyclass
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=pressure
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=rapl
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=schedstat
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=sockstat
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=softnet
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=stat
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=textfile
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=thermal_zone
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=time
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=timex
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=udp_queues
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=uname
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=vmstat
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=xfs
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:112 collector=zfs
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=node_exporter.go:191 msg="Listening on" address=127.0.0.1:9100
node_exporter    | level=info ts=2021-12-02T20:03:47.260Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false
node_exporter    | level=info ts=2021-12-02T20:25:26.368Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
node_exporter    | level=info ts=2021-12-02T20:25:26.368Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:105 msg="Enabled collectors"
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=arp
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=bcache
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=bonding
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=btrfs
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=conntrack
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=cpu
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=cpufreq
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=diskstats
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=edac
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=entropy
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=filefd
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=filesystem
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=hwmon
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=infiniband
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=ipvs
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=loadavg
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=mdadm
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=meminfo
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=netclass
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=netdev
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=netstat
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=nfs
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=nfsd
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=powersupplyclass
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=pressure
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=rapl
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=schedstat
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=sockstat
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=softnet
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=stat
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=textfile
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=thermal_zone
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=time
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=timex
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=udp_queues
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=uname
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=vmstat
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=xfs
node_exporter    | level=info ts=2021-12-02T20:25:26.369Z caller=node_exporter.go:112 collector=zfs
node_exporter    | level=info ts=2021-12-02T20:25:26.370Z caller=node_exporter.go:191 msg="Listening on" address=127.0.0.1:9100
node_exporter    | level=info ts=2021-12-02T20:25:26.370Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false
node_exporter    | level=info ts=2021-12-02T20:59:50.439Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
node_exporter    | level=info ts=2021-12-02T20:59:50.439Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:105 msg="Enabled collectors"
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=arp
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=bcache
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=bonding
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=btrfs
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=conntrack
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=cpu
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=cpufreq
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=diskstats
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=edac
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=entropy
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=filefd
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=filesystem
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=hwmon
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=infiniband
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=ipvs
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=loadavg
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=mdadm
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=meminfo
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=netclass
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=netdev
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=netstat
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=nfs
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=nfsd
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=powersupplyclass
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=pressure
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=rapl
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=schedstat
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=sockstat
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=softnet
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=stat
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=textfile
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=thermal_zone
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=time
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=timex
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=udp_queues
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=uname
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=vmstat
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=xfs
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:112 collector=zfs
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=node_exporter.go:191 msg="Listening on" address=127.0.0.1:9100
node_exporter    | level=info ts=2021-12-02T20:59:50.440Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false
node_exporter    | level=info ts=2021-12-03T17:18:11.118Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
node_exporter    | level=info ts=2021-12-03T17:18:11.118Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:105 msg="Enabled collectors"
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=arp
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=bcache
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=bonding
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=btrfs
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=conntrack
node_exporter    | level=info ts=2021-12-03T17:18:11.119Z caller=node_exporter.go:112 collector=cpu
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=cpufreq
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=diskstats
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=edac
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=entropy
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=filefd
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=filesystem
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=hwmon
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=infiniband
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=ipvs
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=loadavg
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=mdadm
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=meminfo
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=netclass
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=netdev
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=netstat
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=nfs
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=nfsd
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=powersupplyclass
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=pressure
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=rapl
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=schedstat
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=sockstat
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=softnet
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=stat
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=textfile
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=thermal_zone
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=time
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=timex
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=udp_queues
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=uname
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=vmstat
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=xfs
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:112 collector=zfs
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=node_exporter.go:191 msg="Listening on" address=127.0.0.1:9100
node_exporter    | level=info ts=2021-12-03T17:18:11.120Z caller=tls_config.go:170 msg="TLS is disabled and it cannot be enabled on the fly." http2=false

**Comment by greenstatic** [comment] 2021-12-06 08:16
These are the logs for node_exporter (which collects server metrics) not for bbb_exporter. Copy the output of
```shell
$ docker ps
```

**Comment by Nick64M** [comment] 2021-12-06 08:46
There's a lot. I think that's enough?
bbb-exporter     | 2021-12-06 10:42:07,318 [INFO]: Collecting metrics from BigBlueButton API
bbb-exporter     | 2021-12-06 10:42:07,391 [INFO]: Path /var/bigbluebutton/recording/process/presentation doesn't exist, setting processing recordings to 0
bbb-exporter     | 2021-12-06 10:42:07,392 [INFO]: Finished collecting metrics from BigBlueButton API

**Comment by greenstatic** [comment] 2021-12-06 09:03
This seems like the response from the API is successful. The online panel from Grafana uses the Prometheus query: `bbb_api_up`. Check your Prometheus server if everything is in order (if the bbb exporter target is successfully scraped).

**Comment by Nick64M** [comment] 2021-12-06 09:15
Ok

**Comment by greenstatic** [comment] 2022-06-02 09:35
I'll be closing this issue for now, feel free to reopen in case the issue is not solved.

**Closed by greenstatic** 2022-06-02 09:35 UTC
Labels: support
