### ISSUE TITLE
Everything online but no BBB data update

### ISSUE THREAD

**Issue by fmfgroup** [greenstatic/bigbluebutton-exporter#130] opened 2024-04-03 15:31 UTC
Hi, 
I got to have everything online with your full stack tutorial but BBB data is not scraping anything. 
I already checked prometheus and everything seems to be online, but I cannot collect any BBB data (meetings, connections, or anything else). 
<img width="1728" alt="Screenshot 2024-04-03 alle 17 26 26" src="https://github.com/greenstatic/bigbluebutton-exporter/assets/80172050/8b751724-187f-426c-b046-79c77c3a7808">
<img width="1723" alt="Screenshot 2024-04-03 alle 17 29 59" src="https://github.com/greenstatic/bigbluebutton-exporter/assets/80172050/39794952-bfaf-4ef2-bde3-1f143d8a974d">

I already tried to configure docker machines again, doing a docker prune also, but anything changed. 
Please can you help me? 

Thanks

Andrea

**Comment by greenstatic** [comment] 2024-04-03 15:38
Could you try the docker [tag v0.6.1](https://hub.docker.com/layers/greenstatic/bigbluebutton-exporter/v0.6.1/images/sha256-9d9554c5d81575af7c04b2698d6c2fcf2be92bad1faddc489c2b43ca11156629?context=explore) and report back if it works?

**Comment by fmfgroup** [comment] 2024-04-03 15:58
Yes! With 0.6.1 it's working

**Comment by greenstatic** [comment] 2024-04-03 16:09
I assume it is because of this: https://github.com/greenstatic/bigbluebutton-exporter/issues/128
I just merged the author's PR and will make a bugfix release. I'll kindly ask if you could test it out. I'll let you know once it is available.

**Comment by greenstatic** [comment] 2024-04-03 16:13
I merged the PR into main, so you can test out the `latest` docker tag.
Could you:
```sh
docker pull greenstatic/bigbluebutton-exporter:latest
```

and then set the exporter's docker image to `greenstatic/bigbluebutton-exporter:latest`.
The version will be reported still `v0.7.0` but rest assured if you ran the docker pull command you will get the current main branch (which includes the fix).

Report back if you can see the metrics. It should work like with `v0.6.1`

**Comment by fmfgroup** [comment] 2024-04-03 16:27
Yes, I can confirm that the fix is working perfectly! Thank you very much! 

<img width="1726" alt="Screenshot 2024-04-03 alle 18 26 59" src="https://github.com/greenstatic/bigbluebutton-exporter/assets/80172050/fa1d19bb-843c-4959-a664-158eba692bcf">

**Comment by greenstatic** [comment] 2024-04-03 17:01
Perfect, thanks for letting me know. I'll make a bugfix release today.

**Comment by greenstatic** [comment] 2024-04-04 07:51
Just made the release, you can change the docker image tag to `v0.7.1`. 

Release: https://github.com/greenstatic/bigbluebutton-exporter/releases/tag/v0.7.1

**Closed by greenstatic** 2024-04-04 07:51 UTC
Labels: bug, bug-confirmed

**Comment by greenstatic** [comment] 2025-09-03 13:54
> Hello, work nice. But the when I run the docker logs -f bbb-exporter , I see the logs: [ERROR]: HTTPSConnectionPool(host='bbb.domain.com', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=15763d060b6e75936ecc95229de8b82a47a75ec7&state=unpublished (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1135)'))) [INFO]: Finished collecting metrics from BigBlueButton API How I correct the docker to make it to work. Because the error in log my in Grafana show BBB API localhost Offline

Seem to me like you don't have a valid SSL cert.

**Comment by linuxmangr** [comment] 2025-09-04 08:08
> > Hello, work nice. But the when I run the docker logs -f bbb-exporter , I see the logs: [ERROR]: HTTPSConnectionPool(host='bbb.domain.com', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=15763d060b6e75936ecc95229de8b82a47a75ec7&state=unpublished (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1135)'))) [INFO]: Finished collecting metrics from BigBlueButton API How I correct the docker to make it to work. Because the error in log my in Grafana show BBB API localhost Offline
> 
> Seem to me like you don't have a valid SSL cert.

Hi,
I have valid SSL cert on BigBlueButton and Greenlight show it nice.
When I start dockers  bigbluebutton-exporter:v0.7.1 , grafana and prometheus the bbb-exporter take the hostname of host when running BBB and Greenliht .
My BBB version is : BigBlueButton Server 3.0.13 (2904), greenlight-v3 bigbluebutton/greenlight:v3
After start the bbb-exporter and all others a I have the errors:
[ERROR]: HTTPSConnectionPool(host='bbb.domain.com', port=443): Max retries exceeded with url: /bigbluebutton/api/getRecordings?checksum=8c4495b33c4397dae50fe6cb8c2b84c6ac6ba207&state=published (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1135)')))
My metrics report is 
`# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 81172.0
python_gc_objects_collected_total{generation="1"} 7471.0
python_gc_objects_collected_total{generation="2"} 556.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 203.0
python_gc_collections_total{generation="1"} 18.0
python_gc_collections_total{generation="2"} 1.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="19",version="3.8.19"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 3.3898496e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.8516352e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.75681225351e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 12.459999999999999
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 6.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP bbb_meetings Number of BigBlueButton meetings
# TYPE bbb_meetings gauge
bbb_meetings 0.0
# HELP bbb_meetings_participants Total number of participants in all BigBlueButton meetings
# TYPE bbb_meetings_participants gauge
bbb_meetings_participants 0.0
# HELP bbb_meetings_participants_max Maximum number of participants in all BigBlueButton meetings
# TYPE bbb_meetings_participants_max gauge
bbb_meetings_participants_max 0.0
# HELP bbb_meetings_listeners Total number of listeners in all BigBlueButton meetings
# TYPE bbb_meetings_listeners gauge
bbb_meetings_listeners 0.0
# HELP bbb_meetings_voice_participants Total number of voice participants in all BigBlueButton meetings
# TYPE bbb_meetings_voice_participants gauge
bbb_meetings_voice_participants 0.0
# HELP bbb_meetings_video_participants Total number of video participants in all BigBlueButton meetings
# TYPE bbb_meetings_video_participants gauge
bbb_meetings_video_participants 0.0
# HELP bbb_meetings_participant_clients Total number of participants in all BigBlueButton meetings by client
# TYPE bbb_meetings_participant_clients gauge
bbb_meetings_participant_clients{type="html5"} 0.0
bbb_meetings_participant_clients{type="dial-in"} 0.0
# HELP bbb_meetings_participants_origin Total number of participants in all BigBlueButton meetings by origin servername
# TYPE bbb_meetings_participants_origin gauge
# HELP bbb_recordings_unpublished Total number of BigBlueButton recordings unpublished
# TYPE bbb_recordings_unpublished gauge
bbb_recordings_unpublished 0.0
# HELP bbb_recordings_processing Total number of BigBlueButton recordings processing (scraped from disk)
# TYPE bbb_recordings_processing gauge
bbb_recordings_processing 0.0
# HELP bbb_recordings_published Total number of BigBlueButton recordings published (scraped from disk)
# TYPE bbb_recordings_published gauge
bbb_recordings_published 0.0
# HELP bbb_recordings_deleted Total number of BigBlueButton recordings deleted (scraped from disk)
# TYPE bbb_recordings_deleted gauge
bbb_recordings_deleted 0.0
# HELP bbb_recordings_unprocessed Total number of BigBlueButton recordings enqueued to be processed (scraped from disk)
# TYPE bbb_recordings_unprocessed gauge
bbb_recordings_unprocessed 0.0
# HELP bbb_api_latency BigBlueButton API call latency
# TYPE bbb_api_latency histogram
bbb_api_latency_bucket{endpoint="getMeetings",le="0.01",parameters=""} 0.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.025",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.05",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.075",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.1",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.25",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.5",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="0.75",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="1.0",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="1.25",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="1.5",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="1.75",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="2.0",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="2.5",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="5.0",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="7.5",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="10.0",parameters=""} 323.0
bbb_api_latency_bucket{endpoint="getMeetings",le="+Inf",parameters=""} 323.0
bbb_api_latency_count{endpoint="getMeetings",parameters=""} 323.0
bbb_api_latency_sum{endpoint="getMeetings",parameters=""} 5.52035927772522
bbb_api_latency_bucket{endpoint="getRecordings",le="0.01",parameters="state=unpublished"} 0.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.025",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.05",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.075",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.1",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.25",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.5",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="0.75",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="1.0",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="1.25",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="1.5",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="1.75",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="2.0",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="2.5",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="5.0",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="7.5",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="10.0",parameters="state=unpublished"} 323.0
bbb_api_latency_bucket{endpoint="getRecordings",le="+Inf",parameters="state=unpublished"} 323.0
bbb_api_latency_count{endpoint="getRecordings",parameters="state=unpublished"} 323.0
bbb_api_latency_sum{endpoint="getRecordings",parameters="state=unpublished"} 5.413263559341431
# HELP bbb_api_up 1 if BigBlueButton API is responding 0 otherwise
# TYPE bbb_api_up gauge
bbb_api_up 0.0
# HELP bbb_room_participants BigBlueButton room participants histogram gauge
# TYPE bbb_room_participants histogram
bbb_room_participants_bucket{le="0"} 0.0
bbb_room_participants_bucket{le="1"} 0.0
bbb_room_participants_bucket{le="5"} 0.0
bbb_room_participants_bucket{le="15"} 0.0
bbb_room_participants_bucket{le="30"} 0.0
bbb_room_participants_bucket{le="60"} 0.0
bbb_room_participants_bucket{le="90"} 0.0
bbb_room_participants_bucket{le="120"} 0.0
bbb_room_participants_bucket{le="150"} 0.0
bbb_room_participants_bucket{le="200"} 0.0
bbb_room_participants_bucket{le="250"} 0.0
bbb_room_participants_bucket{le="300"} 0.0
bbb_room_participants_bucket{le="400"} 0.0
bbb_room_participants_bucket{le="500"} 0.0
bbb_room_participants_bucket{le="+Inf"} 0.0
# HELP bbb_room_participants_gcount BigBlueButton room participants histogram gauge
# TYPE bbb_room_participants_gcount gauge
bbb_room_participants_gcount 0.0
# HELP bbb_room_participants_gsum BigBlueButton room participants histogram gauge
# TYPE bbb_room_participants_gsum gauge
bbb_room_participants_gsum 0.0
# HELP bbb_room_listeners BigBlueButton room listeners histogram gauge
# TYPE bbb_room_listeners histogram
bbb_room_listeners_bucket{le="0"} 0.0
bbb_room_listeners_bucket{le="1"} 0.0
bbb_room_listeners_bucket{le="5"} 0.0
bbb_room_listeners_bucket{le="15"} 0.0
bbb_room_listeners_bucket{le="30"} 0.0
bbb_room_listeners_bucket{le="60"} 0.0
bbb_room_listeners_bucket{le="90"} 0.0
bbb_room_listeners_bucket{le="120"} 0.0
bbb_room_listeners_bucket{le="150"} 0.0
bbb_room_listeners_bucket{le="200"} 0.0
bbb_room_listeners_bucket{le="250"} 0.0
bbb_room_listeners_bucket{le="300"} 0.0
bbb_room_listeners_bucket{le="400"} 0.0
bbb_room_listeners_bucket{le="500"} 0.0
bbb_room_listeners_bucket{le="+Inf"} 0.0
# HELP bbb_room_listeners_gcount BigBlueButton room listeners histogram gauge
# TYPE bbb_room_listeners_gcount gauge
bbb_room_listeners_gcount 0.0
# HELP bbb_room_listeners_gsum BigBlueButton room listeners histogram gauge
# TYPE bbb_room_listeners_gsum gauge
bbb_room_listeners_gsum 0.0
# HELP bbb_room_voice_participants BigBlueButton room voice participants histogram gauge
# TYPE bbb_room_voice_participants histogram
bbb_room_voice_participants_bucket{le="0"} 0.0
bbb_room_voice_participants_bucket{le="1"} 0.0
bbb_room_voice_participants_bucket{le="5"} 0.0
bbb_room_voice_participants_bucket{le="15"} 0.0
bbb_room_voice_participants_bucket{le="30"} 0.0
bbb_room_voice_participants_bucket{le="60"} 0.0
bbb_room_voice_participants_bucket{le="90"} 0.0
bbb_room_voice_participants_bucket{le="120"} 0.0
bbb_room_voice_participants_bucket{le="+Inf"} 0.0
# HELP bbb_room_voice_participants_gcount BigBlueButton room voice participants histogram gauge
# TYPE bbb_room_voice_participants_gcount gauge
bbb_room_voice_participants_gcount 0.0
# HELP bbb_room_voice_participants_gsum BigBlueButton room voice participants histogram gauge
# TYPE bbb_room_voice_participants_gsum gauge
bbb_room_voice_participants_gsum 0.0
# HELP bbb_room_video_participants BigBlueButton room video participants histogram gauge
# TYPE bbb_room_video_participants histogram
bbb_room_video_participants_bucket{le="0"} 0.0
bbb_room_video_participants_bucket{le="1"} 0.0
bbb_room_video_participants_bucket{le="5"} 0.0
bbb_room_video_participants_bucket{le="15"} 0.0
bbb_room_video_participants_bucket{le="30"} 0.0
bbb_room_video_participants_bucket{le="60"} 0.0
bbb_room_video_participants_bucket{le="90"} 0.0
bbb_room_video_participants_bucket{le="120"} 0.0
bbb_room_video_participants_bucket{le="+Inf"} 0.0
# HELP bbb_room_video_participants_gcount BigBlueButton room video participants histogram gauge
# TYPE bbb_room_video_participants_gcount gauge
bbb_room_video_participants_gcount 0.0
# HELP bbb_room_video_participants_gsum BigBlueButton room video participants histogram gauge
# TYPE bbb_room_video_participants_gsum gauge
bbb_room_video_participants_gsum 0.0
# HELP bbb_unique_meetings_total Unique non-breakout meetings counter
# TYPE bbb_unique_meetings_total counter
bbb_unique_meetings_total 0.0
# HELP bbb_unique_breakout_rooms_total Unique breakout rooms counter
# TYPE bbb_unique_breakout_rooms_total counter
bbb_unique_breakout_rooms_total 0.0
# HELP bbb_version BigBlueButton version
# TYPE bbb_version gauge
bbb_version{version="3.0.13"} 1.0
# HELP bbb_exporter BigBlueButton Exporter version
# TYPE bbb_exporter gauge
bbb_exporter{version="0.7.1"} 1.0
`
